### ISSUE TITLE
ck_setup() - Long execution time - Unable to generate hypercubes with more than 6 dimensions

### ISSUE THREAD

**Issue by vanessa-azzopardi-work** [sdcTools/cellKey#16]
Hi,

I am currently extracting Census hypercubes using the function `ck_setup()` from the package `cellKey`.  The issue I am facing is that the execution time is excessively long.  I would like to understand whether I am working inefficiently or missing something.

The code in the extract below ran for 5 hours, at which point I decided to stop the process and therefore was unable to generate this hypercube.  The same thing happens with any other hypercube of similar size (8 dimensions).

```
# Defining the dimensions of hypercube 6
dims6 <- list(GEO.L = dim_geo.l, SEX=dim_sex, AGE.M=dim_age.m, LPW.N=dim_lpw.n, OCC=dim_occ, IND.L=dim_ind.l, SIE=dim_sie, EDU=dim_edu)

# Setting up a table instance for hypercube 6
hc_6 <- cellKey::ck_setup(x = data, rkey = "r_keys", dims = dims6, w = NULL) 
```

For comparison, the following code took around 15 minutes to execute and I was able to generate the hypercube.  Therefore, at the moment, I am only able to generate hypercubes having 6 dimensions or less.

```
# Defining the dimensions of hypercube 1
dims1 <- list(GEO.N = dim_geo.n, SEX = dim_sex, AGE.H = dim_age.h, LMS.H=dim_lms.h, HST.H=dim_hst.h, FST.H=dim_fst.h)                             				      

# Setting up a table instance for hypercube 1
hc_1 <- cellKey::ck_setup(x = data, rkey = "r_keys", dims = dims1, w = NULL)
```

Is it normal for the execution to take so long or am I doing something which is slowing the process down?  What can I do to be able to generate the hypercubes having more than 6 dimensions?

To provide further detail on the problem, I am attaching the R workspace image file containing the hierarchies I am using ([WorkspaceImage_VA.zip](https://github.com/sdcTools/cellKey/files/13195734/WorkspaceImage_VA.zip)).  The data itself is not provided but it is in the format of a data frame with 59 variables and 413267 observations.  One of the variables (r_keys) contains the record keys.  There are no weights.

Looking forward to your feedback.

**Comment by bernhard-da** [comment]
@vanessa-azzopardi thx for your summary; The long running computation times are explainable because in `ck_setup()` for each (sub)total cell the cells that contribute to this cell were identified where the running-time increases with the number of sub-total cells. This information is required however only if numerical variables need to be perturbed. In your example case this is not the case  and thus I modified code in https://github.com/sdcTools/cellKey/commit/12d0abf190f6874d0c46f0be810109d53c80bb06 so that these computations are done only if argument `numvars` in `ck_setup()` is not empty. 

Before I upload a new CRAN version, it would be nice if you could try this out: To install, you could either use:
```
remotes::install_github("sdcTools/cellKey, ref = "fixes_performance")
```
or install the zip-file from win-builder (only valid for ~72hours from now on) located [`here`](https://win-builder.r-project.org/6kTzZREhLz7d/cellKey_1.0.2.zip)

**Comment by vanessa-azzopardi-work** [comment]
@bernhard-da thank you, this makes sense.

I have tested the updated version of the package and it has improved the processing time tremendously.  Processes which took 5 hours to complete were reduced to around 20 minutes.  Clearly the problem was the one you identified in your reply.

Thank you very much for the explanation and fix.  Very helpful, as always :)

**Comment by bernhard-da** [comment]
new version of cellKey (`1.0.2`) is on its way to CRAN.
